# This is a basic workflow to help you get started with Actions

name: my-github-basics

on:
  push:
    branches: [master]
jobs:
  my_testing:  
    runs-on: ubuntu-latest 
    steps:
     - name: Print hello world
        run: echo "Hello world"
  my_deploy: 
   runs-on: ubuntu-latest 
    steps:    
     - name: Print hello world
        run: echo "Hello world"
